import type { KpiItem, MortgageDossier } from "./types";

/** Mock dossiers for UI development. Replace with API data later. */
export const mockDossiers: MortgageDossier[] = [
  {
    id: "dos-001",
    clientName: "Jansen, T.",
    advisor: "René de Boer",
    lender: "Rabobank",
    principal: 450000,
    applicationDate: "2026-08-12",
    conditionalDate: "2026-09-28",
    closingDate: "2026-10-15",
    phase: "In behandeling",
  },
  {
    id: "dos-002",
    clientName: "de Vries, M.",
    advisor: "Sanne Jansen",
    lender: "ING",
    principal: 325000,
    applicationDate: "2026-08-05",
    conditionalDate: "2026-09-20",
    closingDate: "2026-10-10",
    phase: "In behandeling",
  },
  {
    id: "dos-003",
    clientName: "van Dijk, R.",
    advisor: "Marco Visser",
    lender: "ABN AMRO",
    principal: 520000,
    applicationDate: "2026-08-03",
    conditionalDate: "2026-09-18",
    closingDate: "2026-09-24",
    phase: "In behandeling",
  },
  {
    id: "dos-004",
    clientName: "Bakker, L.",
    advisor: "René de Boer",
    lender: "Aegon",
    principal: 275000,
    applicationDate: "2026-07-28",
    conditionalDate: "2026-09-15",
    closingDate: "2026-10-02",
    phase: "In behandeling",
  },
  {
    id: "dos-005",
    clientName: "Meijer, S.",
    advisor: "Sanne Jansen",
    lender: "Florius",
    principal: 410000,
    applicationDate: "2026-08-18",
    conditionalDate: "2026-10-01",
    closingDate: "2026-10-28",
    phase: "In behandeling",
  },
  {
    id: "dos-006",
    clientName: "Smit, K.",
    advisor: "Marco Visser",
    lender: "Rabobank",
    principal: 680000,
    applicationDate: "2026-07-15",
    conditionalDate: "2026-09-12",
    closingDate: "2026-09-30",
    phase: "In behandeling",
  },
  {
    id: "dos-007",
    clientName: "Mulder, A.",
    advisor: "Lisa van den Berg",
    lender: "ING",
    principal: 295000,
    applicationDate: "2026-08-22",
    conditionalDate: "2026-10-05",
    closingDate: "2026-11-12",
    phase: "In behandeling",
  },
  {
    id: "dos-008",
    clientName: "de Boer, P.",
    advisor: "René de Boer",
    lender: "Obvion",
    principal: 385000,
    applicationDate: "2026-08-01",
    conditionalDate: "2026-09-22",
    closingDate: "2026-10-08",
    phase: "In behandeling",
  },
  {
    id: "dos-009",
    clientName: "Visser, H.",
    advisor: "Lisa van den Berg",
    lender: "ABN AMRO",
    principal: 540000,
    applicationDate: "2026-07-20",
    conditionalDate: "2026-09-10",
    closingDate: "2026-09-26",
    phase: "In behandeling",
  },
  {
    id: "dos-010",
    clientName: "Peters, N.",
    advisor: "Sanne Jansen",
    lender: "Nationale-Nederlanden",
    principal: 370000,
    applicationDate: "2026-08-10",
    conditionalDate: "2026-09-30",
    closingDate: "2026-10-20",
    phase: "In behandeling",
  },
];

export const inBehandelingKpis: KpiItem[] = [
  {
    id: "kpi-dossiers",
    value: "18",
    label: "Dossiers in behandeling",
    icon: "folder",
  },
  {
    id: "kpi-principal",
    value: "€ 6.250.000",
    label: "Totale hoofdsom",
    icon: "euro",
  },
  {
    id: "kpi-closing",
    value: "5",
    label: "Passeerdatum komende 14 dagen",
    icon: "calendar",
  },
  {
    id: "kpi-conditional",
    value: "3",
    label: "Ontbindende voorwaarden komende 14 dagen",
    icon: "clock",
  },
];

export const mockAdvisors = [
  "René de Boer",
  "Sanne Jansen",
  "Marco Visser",
  "Lisa van den Berg",
] as const;

export const mockLenders = [
  "Rabobank",
  "ING",
  "ABN AMRO",
  "Aegon",
  "Florius",
  "Obvion",
  "Nationale-Nederlanden",
] as const;
